### ISSUE TITLE
Setting OperatorPipelinesRelease does not fetch the version

### ISSUE THREAD

**Issue by sxd** [redhat-openshift-ecosystem/operator-certification-operator#150]
## Bug Description

When setting the `OperatorPipelinesRelease` for OperatorPipeline like this:

```
operatorCertification.OperatorPipeline{
		ObjectMeta: metav1.ObjectMeta{
			Name:      PipelineName,
			Namespace: testingNamespace,
		},
		Spec: operatorCertification.OperatorPipelineSpec{
			ApplyCIPipeline:          true,
			ApplyHostedPipeline:      false,
			ApplyReleasePipeline:     false,
			GitHubSecretName:         githubSecretName,
			KubeconfigSecretName:     kubeconfigSecretName,
			OperatorPipelinesRelease: "v1.0.98",
			PyxisSecretName:          pyxisSecretName,
		},
	}
```

When running this I get this error:
```
status:
  conditions:
  - lastTransitionTime: "2023-10-25T14:05:35Z"
    message: Local repo unavailable
    observedGeneration: 1
    reason: NotFound
    status: "False"
    type: GitRepoReady
  observedGeneration: 1
```
Looks like everything is related to this part of the code https://github.com/redhat-openshift-ecosystem/operator-certification-operator/blob/main/internal/reconcilers/pipeline_git_repo.go#L59 where we only get a branch and not the tag, so we don't get a `Release` but rather we only get a branch.

This is kind of difficult when there's a small change like the one reported here https://github.com/redhat-openshift-ecosystem/operator-pipelines/issues/530 because we should be getting a version to run the certification pipeline
