### ISSUE TITLE
Operator Fails to Deploy via CatalogSource

### ISSUE THREAD

**Issue by acornett21** [redhat-openshift-ecosystem/operator-certification-operator#52]
## Bug Description
The operator fails to deploy via a catalog source. I believe the issue is that the `image` tag in the bundle does not point to a valid  container image, nor does the code checked into the `main` branch of this repo.

## Version and Command Invocation
sha of bundle in quay `5c3f130d9a450b2b43720df594f203b058cc9554`

## Steps to Reproduce:
1) Create a `CatalogSource` with `quay.io/opdev/operator-certification-operator-bundle:5c3f130d9a450b2b43720df594f203b058cc9554` as the image
2) run `oc apply`
3) tail logs ` kubectl logs -f -n openshift-operator-lifecycle-manager olm-operator-<whateveridofrunningpod>`

## Expected Result
I expect to be able to run this operator via a catalog source so that it shows up in operator hub.

## Actual Result
Operator does not appear in the catalog.

## Additional Context
CatalogSource
```
oc apply -f - <<'EOF'
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: operator-certification-operator
  namespace: openshift-marketplace
spec:
  displayName: Operator Certification Operator
  icon:
    base64data: ""
    mediatype: ""
  image: quay.io/opdev/operator-certification-operator-bundle:5c3f130d9a450b2b43720df594f203b058cc9554
  priority: -200
  publisher: Red Hat
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 10m0s
EOF
```

Error
```

{
  "level": "error",
  "ts": 1637185074.8848817,
  "logger": "controller-runtime.manager.controller.operatorcondition",
  "msg": "Reconciler error",
  "reconciler group": "operators.coreos.com",
  "reconciler kind": "OperatorCondition",
  "name": "operator-certification-operator.v0.0.0-alpha",
  "namespace": "oco",
  "error": "OperatorCondition.operators.coreos.com \"operator-certification-operator.v0.0.0-alpha\" not found",
  "stacktrace": "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/build/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2\n\t/build/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:216\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\t/build/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/build/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/build/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/build/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\t/build/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\t/build/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:99"
}

```

Image I believe is trying to be pulled based on code in main
`quay.io/opdev/operator-certification-operator:09f54622a8707ebc3e94aaef9a8781cf9bf6cc6d`

podman pull of the above
```
podman pull quay.io/opdev/operator-certification-operator:09f54622a8707ebc3e94aaef9a8781cf9bf6cc6d
Trying to pull quay.io/opdev/operator-certification-operator:09f54622a8707ebc3e94aaef9a8781cf9bf6cc6d...
Error: initializing source docker://quay.io/opdev/operator-certification-operator:09f54622a8707ebc3e94aaef9a8781cf9bf6cc6d: reading manifest 09f54622a8707ebc3e94aaef9a8781cf9bf6cc6d in quay.io/opdev/operator-certification-operator: manifest unknown: manifest unknown
```
